spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: xiaoban12138
  sql:
    init:
      schema-locations:
        - classpath:sql/schema.sql
      mode: always

server:
  port: 9530

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.springboot.demo.domain
  configuration:
    map-underscore-to-camel-case: true
